package voxgig.bluefintecsecrsdk.core

import java.util.{Map => JMap}

import voxgig.bluefintecsecrsdk.utility.Json

// Static SDK configuration and by-name feature construction.
object Config {

  def makeConfig(): JMap[String, Object] =
    Json.parse(configJson()).asInstanceOf[JMap[String, Object]]

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // A lazy val is initialised once, on first use, under a lock, so
  // concurrent first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private lazy val sharedConfigVal: JMap[String, Object] = makeConfig()

  def sharedConfig(): JMap[String, Object] = sharedConfigVal

  def makeFeature(name: String): Feature = name match {
    case "audit" => new voxgig.bluefintecsecrsdk.feature.AuditFeature()
    case "clienttrack" => new voxgig.bluefintecsecrsdk.feature.ClienttrackFeature()
    case "idempotency" => new voxgig.bluefintecsecrsdk.feature.IdempotencyFeature()
    case "log" => new voxgig.bluefintecsecrsdk.feature.LogFeature()
    case "metrics" => new voxgig.bluefintecsecrsdk.feature.MetricsFeature()
    case "paging" => new voxgig.bluefintecsecrsdk.feature.PagingFeature()
    case "ratelimit" => new voxgig.bluefintecsecrsdk.feature.RatelimitFeature()
    case "retry" => new voxgig.bluefintecsecrsdk.feature.RetryFeature()
    case "telemetry" => new voxgig.bluefintecsecrsdk.feature.TelemetryFeature()
    case "test" => new voxgig.bluefintecsecrsdk.feature.TestFeature()
    case "timeout" => new voxgig.bluefintecsecrsdk.feature.TimeoutFeature()
    case _ => new voxgig.bluefintecsecrsdk.feature.BaseFeature()
  }

  private def configJson(): String = {
    val b = new StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinTecsEcr\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"audit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"actor\": \"anonymous\",")
    b.append("    \"max\": 1000")
    b.append("   }")
    b.append("  },")
    b.append("  \"clienttrack\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"clientVersion\": \"0.0.1\"")
    b.append("   }")
    b.append("  },")
    b.append("  \"idempotency\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"header\": \"Idempotency-Key\",")
    b.append("    \"methods\": [")
    b.append("     \"POST\",")
    b.append("     \"PUT\",")
    b.append("     \"PATCH\",")
    b.append("     \"DELETE\"")
    b.append("    ],")
    b.append("    \"ops\": [")
    b.append("     \"create\",")
    b.append("     \"update\",")
    b.append("     \"remove\"")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"log\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": true")
    b.append("   }")
    b.append("  },")
    b.append("  \"metrics\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"paging\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"afterVar\": \"after\",")
    b.append("    \"cursorParam\": \"cursor\",")
    b.append("    \"firstVar\": \"first\",")
    b.append("    \"limitParam\": \"limit\",")
    b.append("    \"pageParam\": \"page\",")
    b.append("    \"startPage\": 1")
    b.append("   }")
    b.append("  },")
    b.append("  \"ratelimit\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"burst\": 5,")
    b.append("    \"rate\": 5")
    b.append("   }")
    b.append("  },")
    b.append("  \"retry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"factor\": 2,")
    b.append("    \"maxDelay\": 2000,")
    b.append("    \"minDelay\": 50,")
    b.append("    \"retries\": 2,")
    b.append("    \"statuses\": [")
    b.append("     408,")
    b.append("     425,")
    b.append("     429,")
    b.append("     500,")
    b.append("     502,")
    b.append("     503,")
    b.append("     504")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"telemetry\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  },")
    b.append("  \"timeout\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false,")
    b.append("    \"ms\": 30000")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://test.tecs.at/tecsclientrest-auth\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Bearer\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"ecr_api\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"ecr_api\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"amount\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Numeric Transaction Amount.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"authorization_number\",")
    b.append("     \"short\": \"For Gratuity (msg type 0009): the authorization number of the original transaction.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"card_number\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Depends on the transaction scenario: - **Standard Pin Pad transaction:** leave empty.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"currency\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"ISO 4217 Alpha Currency Code (e.g., \\\"EUR\\\", \\\"USD\\\").\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"cvc2\",")
    b.append("     \"short\": \"Card Verification Code.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"desired_currency\",")
    b.append("     \"short\": \"ISO 4217 Alpha Currency Code in which the transaction will be processed (e.g., \\\"EUR\\\", \\\"USD\\\").\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"ecr_data\",")
    b.append("     \"short\": \"ECR Data field used to transfer user information for private-labeled cards (e.g., Fleet Card Company such as UTA, outex).\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"language\",")
    b.append("     \"short\": \"ISO 639-1 language code used by the Pin Pad user interface during the transaction (e.g., \\\"en\\\", \\\"de\\\", \\\"es\\\").\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"message_type\",")
    b.append("     \"short\": \"Message type code.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"password\",")
    b.append("     \"short\": \"Password - currently not used (filled with spaces).\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"payment_reason\",")
    b.append("     \"short\": \"Payment reason (e.g., \\\"Taxi journey\\\").\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"payment_reasonAsByte\",")
    b.append("     \"short\": \"Payment reason represented as a byte array.\",")
    b.append("     \"type\": \"`$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"personal_id\",")
    b.append("     \"short\": \"Identification of the current user of the ECR or Terminal.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"receipt_layout\",")
    b.append("     \"short\": \"Receipt layout identifier.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"receipt_number\",")
    b.append("     \"short\": \"Receipt number.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminal_number\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Terminal number provided by TECS.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_date_time\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Transaction date and time (format: yyyymmddhhmmss).\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_id\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique transaction identifier.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_origin_identifier\",")
    b.append("     \"short\": \"Transaction origin identifier: - 1 = Face to Face (Customer present) - 2 = MOTO (Customer not present) - 4 = Capture/Completion - 5 = Pre Authorization - 7 = Balance\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_origin_indicator\",")
    b.append("     \"short\": \"Transaction origin indicator: - 0 = Request for card data on PIN PAD.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_place\",")
    b.append("     \"short\": \"The transaction place; the first 5 characters should contain a formatted zip code.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_source_id\",")
    b.append("     \"short\": \"Identification number of the authorization source.\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"ecr_api\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/makeTransaction\",")
    b.append("       \"parts\": [")
    b.append("        \"makeTransaction\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/version\",")
    b.append("       \"parts\": [")
    b.append("        \"version\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    b.toString
  }
}
