package voxgig.bluefintecsecrsdk.core

import java.util.{Map => JMap}

import voxgig.bluefintecsecrsdk.utility.Json

// Static SDK configuration and by-name feature construction.
object Config {

  def makeConfig(): JMap[String, Object] =
    Json.parse(configJson()).asInstanceOf[JMap[String, Object]]

  def makeFeature(name: String): Feature = name match {
    case "test" => new voxgig.bluefintecsecrsdk.feature.TestFeature()
    case _ => new voxgig.bluefintecsecrsdk.feature.BaseFeature()
  }

  private def configJson(): String = {
    val b = new StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinTecsEcr\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://test.tecs.at/tecsclientrest-auth\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Bearer\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"ecr_api\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"ecr_api\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"amount\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"authorization_number\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"card_number\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"currency\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"cvc2\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"desired_currency\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"ecr_data\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"language\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_type\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 8")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"password\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 9")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"payment_reason\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 10")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"payment_reasonAsByte\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 11")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"personal_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 12")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"receipt_layout\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 13")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"receipt_number\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 14")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"terminal_number\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 15")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"transaction_date_time\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 16")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"transaction_id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 17")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"transaction_origin_identifier\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 18")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"transaction_origin_indicator\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 19")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"transaction_place\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 20")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"transaction_source_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 21")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"ecr_api\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/makeTransaction\",")
    b.append("       \"parts\": [")
    b.append("        \"makeTransaction\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/version\",")
    b.append("       \"parts\": [")
    b.append("        \"version\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    b.toString
  }
}
