// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinTecsEcr")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://test.tecs.at/tecsclientrest-auth"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(1,
        "ecr_api", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(1,
      "ecr_api", cmap(4,
        "fields", clist(22,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("amount"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("authorization_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("card_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("cvc2"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("desired_currency"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("ecr_data"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("language"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("message_type"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("password"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("payment_reason"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("payment_reasonAsByte"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("personal_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("receipt_layout"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("receipt_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminal_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transaction_date_time"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transaction_id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transaction_origin_identifier"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transaction_origin_indicator"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transaction_place"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(20)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("transaction_source_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(21))),
        "name", v_str("ecr_api"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/makeTransaction"),
                "parts", clist(1,
                  v_str("makeTransaction")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "active", v_bool(true),
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/version"),
                "parts", clist(1,
                  v_str("version")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
