package voxgig.bluefintecsecrsdk.core

import voxgig.bluefintecsecrsdk.utility.Json

/** Static SDK configuration and by-name feature construction. */
@Suppress("UNCHECKED_CAST")
object Config {

  fun makeConfig(): MutableMap<String, Any?> {
    return Json.parse(configJson()) as MutableMap<String, Any?>
  }

  fun makeFeature(name: String): Feature {
    return when (name) {
      "test" -> voxgig.bluefintecsecrsdk.feature.TestFeature()
      else -> voxgig.bluefintecsecrsdk.feature.BaseFeature()
    }
  }

  private fun configJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinTecsEcr\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://test.tecs.at/tecsclientrest-auth\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"Bearer\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"ecr_api\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"ecr_api\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"amount\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"authorization_number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"card_number\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"currency\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"cvc2\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"desired_currency\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"ecr_data\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"language\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"message_type\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"password\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"payment_reason\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"payment_reasonAsByte\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"personal_id\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"receipt_layout\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"receipt_number\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminal_number\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_date_time\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_origin_identifier\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_origin_indicator\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_place\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"transaction_source_id\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"ecr_api\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/makeTransaction\",")
    b.append("       \"parts\": [")
    b.append("        \"makeTransaction\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/version\",")
    b.append("       \"parts\": [")
    b.append("        \"version\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    return b.toString()
  }
}
