;; BluefinTecsEcr SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.ecr_api :as e-ecr_api]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def graphql client/graphql)
(def prepare client/prepare)
(def options-map client/options-map)

;; EcrApi accessor: (ecr_api client data)
(defn ecr_api [client data] (e-ecr_api/make client data))
