;; BluefinTecsEcr SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "ecr_api" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "amount"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "authorization_number"
            "type" "`$STRING`")
          (vs/jm
            "name" "card_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "cvc2"
            "type" "`$STRING`")
          (vs/jm
            "name" "desired_currency"
            "type" "`$STRING`")
          (vs/jm
            "name" "ecr_data"
            "type" "`$STRING`")
          (vs/jm
            "name" "language"
            "type" "`$STRING`")
          (vs/jm
            "name" "message_type"
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "type" "`$STRING`")
          (vs/jm
            "name" "payment_reason"
            "type" "`$STRING`")
          (vs/jm
            "name" "payment_reasonAsByte"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "personal_id"
            "type" "`$STRING`")
          (vs/jm
            "name" "receipt_layout"
            "type" "`$STRING`")
          (vs/jm
            "name" "receipt_number"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminal_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_date_time"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_origin_identifier"
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_origin_indicator"
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_place"
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_source_id"
            "type" "`$STRING`"))
        "name" "ecr_api"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/makeTransaction"
                "parts" (vs/jt
                  "makeTransaction")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/version"
                "parts" (vs/jt
                  "version")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinTecsEcr")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Bearer")
      "base" "https://test.tecs.at/tecsclientrest-auth"
      "entity" (vs/jm
        "ecr_api" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
