;; BluefinTecsEcr SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "ecr_api" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "amount"
            "req" true
            "short" "Numeric Transaction Amount."
            "type" "`$STRING`")
          (vs/jm
            "name" "authorization_number"
            "short" "For Gratuity (msg type 0009): the authorization number of the original transaction."
            "type" "`$STRING`")
          (vs/jm
            "name" "card_number"
            "req" true
            "short" "Depends on the transaction scenario: - **Standard Pin Pad transaction:** leave empty."
            "type" "`$STRING`")
          (vs/jm
            "name" "currency"
            "req" true
            "short" "ISO 4217 Alpha Currency Code (e.g., \"EUR\", \"USD\")."
            "type" "`$STRING`")
          (vs/jm
            "name" "cvc2"
            "short" "Card Verification Code."
            "type" "`$STRING`")
          (vs/jm
            "name" "desired_currency"
            "short" "ISO 4217 Alpha Currency Code in which the transaction will be processed (e.g., \"EUR\", \"USD\")."
            "type" "`$STRING`")
          (vs/jm
            "name" "ecr_data"
            "short" "ECR Data field used to transfer user information for private-labeled cards (e.g., Fleet Card Company such as UTA, outex)."
            "type" "`$STRING`")
          (vs/jm
            "name" "language"
            "short" "ISO 639-1 language code used by the Pin Pad user interface during the transaction (e.g., \"en\", \"de\", \"es\")."
            "type" "`$STRING`")
          (vs/jm
            "name" "message_type"
            "short" "Message type code."
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "short" "Password - currently not used (filled with spaces)."
            "type" "`$STRING`")
          (vs/jm
            "name" "payment_reason"
            "short" "Payment reason (e.g., \"Taxi journey\")."
            "type" "`$STRING`")
          (vs/jm
            "name" "payment_reasonAsByte"
            "short" "Payment reason represented as a byte array."
            "type" "`$ARRAY`")
          (vs/jm
            "name" "personal_id"
            "short" "Identification of the current user of the ECR or Terminal."
            "type" "`$STRING`")
          (vs/jm
            "name" "receipt_layout"
            "short" "Receipt layout identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "receipt_number"
            "short" "Receipt number."
            "type" "`$STRING`")
          (vs/jm
            "name" "terminal_number"
            "req" true
            "short" "Terminal number provided by TECS."
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_date_time"
            "req" true
            "short" "Transaction date and time (format: yyyymmddhhmmss)."
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_id"
            "req" true
            "short" "Unique transaction identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_origin_identifier"
            "short" "Transaction origin identifier: - 1 = Face to Face (Customer present) - 2 = MOTO (Customer not present) - 4 = Capture/Completion - 5 = Pre Authorization - 7 = Balance"
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_origin_indicator"
            "short" "Transaction origin indicator: - 0 = Request for card data on PIN PAD."
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_place"
            "short" "The transaction place; the first 5 characters should contain a formatted zip code."
            "type" "`$STRING`")
          (vs/jm
            "name" "transaction_source_id"
            "short" "Identification number of the authorization source."
            "type" "`$STRING`"))
        "name" "ecr_api"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/makeTransaction"
                "parts" (vs/jt
                  "makeTransaction")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/version"
                "parts" (vs/jt
                  "version")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "transport" "base"))
    "main" (vs/jm
      "name" "BluefinTecsEcr"
      "slug" "bluefin-tecs-ecr"
      "target" "clojure"
      "version" "0.1.1")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Bearer")
      "base" "https://test.tecs.at/tecsclientrest-auth"
      "entity" (vs/jm
        "ecr_api" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
